#!/usr/bin/env bash
#KOD
i=1
while [ $i -le 20 ]; do
  case $i in
    4)
      echo -e "4\nbad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  i=$((i+1))
done
