#!/usr/bin/env bash
#Process and PID file
PID="/var/run/myscript.pid"
echo "$$" > "$PID"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PID"; exit' SIGQUIT SIGTERM
while true; do
  echo "To infinity and beyond"
done
